stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - params.yaml
    outs:
      - artifacts/data/raw/train.csv
      - artifacts/data/raw/test.csv

  data_preprocessing:
    cmd: python src/components/data_preprocessing.py
    deps:
      - artifacts/data/raw/train.csv
      - artifacts/data/raw/test.csv
      - src/components/data_preprocessing.py
    outs:
      - artifacts/data/processed/train_processed.csv
      - artifacts/data/processed/test_processed.csv

  text_vectorization:
    cmd: python src/components/text_vectorization.py
    deps:
      - artifacts/data/processed/train_processed.csv
      - artifacts/data/processed/test_processed.csv
      - src/components/text_vectorization.py
      - params.yaml
    outs:
      - artifacts/data/vectorized/train_vectorized.csv
      - artifacts/data/vectorized/test_vectorized.csv
      - artifacts/data/vectorized/vectorizer.pkl

  model_trainer:
    cmd: python src/components/model_trainer.py
    deps:
      - artifacts/data/vectorized/train_vectorized.csv
      - src/components/model_trainer.py
      - params.yaml
    outs:
      - artifacts/model/logistic_regression_model.pkl

  model_evaluation:
    cmd: python src/components/model_evaluation.py
    deps:
      - artifacts/data/vectorized/test_vectorized.csv
      - artifacts/model/logistic_regression_model.pkl
      - src/components/model_evaluation.py
      - params.yaml
    outs:
      - reports/metrics.yaml
      - reports/experiment_info.json


  model_registration:
    cmd: python src/components/model_register.py
    deps:
      - src/components/model_register.py
      - reports/experiment_info.json
      - params.yaml
